// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-app-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_app_info_default = defineTool({
  name: "get_app_info",
  title: "Get app info",
  description: "Returns metadata about KodFlip \u2014 a frame-by-frame 2D animation studio for kids: name, description, supported export formats, and canvas capabilities.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "KodFlip",
      tagline: "Animation Studio for Kids",
      description: "A fun, powerful frame-by-frame 2D animation studio in the browser for kids 10\u201314. Draw, animate and export.",
      capabilities: {
        drawingTools: ["pencil", "eraser", "fill", "shapes (line/rect/circle)", "color picker", "selection/transform", "move/pan"],
        layers: true,
        onionSkin: true,
        timeline: true,
        exportFormats: ["Animated GIF", "PNG sequence (.zip)", "Project (.json)"],
        maxCanvas: { width: 1920, height: 1920 }
      },
      author: "Andrei Pobiarzhyn"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-shortcuts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var SHORTCUTS = [
  { keys: "P", action: "Pencil" },
  { keys: "E", action: "Eraser" },
  { keys: "G", action: "Fill" },
  { keys: "S", action: "Select / Transform" },
  { keys: "I", action: "Color picker" },
  { keys: "[ / ]", action: "Decrease / Increase tool size" },
  { keys: "N", action: "New frame" },
  { keys: "D", action: "Duplicate frame" },
  { keys: "Space", action: "Play / Pause" },
  { keys: "\u2190 / \u2192", action: "Previous / Next frame" },
  { keys: "Ctrl+Z", action: "Undo" },
  { keys: "Ctrl+Shift+Z", action: "Redo" },
  { keys: "Scroll", action: "Zoom canvas" },
  { keys: "Shift+Drag", action: "Pan canvas" },
  { keys: "Enter / Esc", action: "Apply / Cancel selection" }
];
var list_shortcuts_default = defineTool2({
  name: "list_keyboard_shortcuts",
  title: "List keyboard shortcuts",
  description: "Returns the full list of keyboard shortcuts available in the KodFlip animation editor.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: SHORTCUTS.map((s) => `${s.keys.padEnd(14)} \u2014 ${s.action}`).join("\n")
      }
    ],
    structuredContent: { shortcuts: SHORTCUTS }
  })
});

// src/lib/mcp/tools/animation-tips.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var TIPS = {
  basics: [
    "Start with a low frame count (4\u20138) and short loops to iterate quickly.",
    "Use onion skin to see the previous frame while drawing the next one.",
    "Duplicate a frame (D) instead of redrawing when only small parts change."
  ],
  timing: [
    "12 fps feels classic and hand-drawn; 24 fps looks smoother.",
    "Hold important poses for 2\u20133 frames to make actions readable.",
    "Add ease-in/ease-out by clustering more frames near the start and end of a move."
  ],
  drawing: [
    "Block big shapes with the shape tools, then refine with the pencil.",
    "Keep the outline on one layer and colors on another so you can recolor freely.",
    "Use the color picker (I) to sample colors instead of remixing them."
  ],
  export: [
    "Animated GIF is best for sharing loops on the web.",
    "PNG sequence gives you full-quality per-frame files for editing elsewhere.",
    "Save the .json project to keep layers and timeline editable later."
  ]
};
var animation_tips_default = defineTool3({
  name: "get_animation_tips",
  title: "Get animation tips",
  description: "Returns short, kid-friendly frame-by-frame animation tips grouped by topic (basics, timing, drawing, export).",
  inputSchema: {
    topic: z.enum(["basics", "timing", "drawing", "export", "all"]).default("all").describe("Which tip category to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topic }) => {
    const selected = topic === "all" ? TIPS : { [topic]: TIPS[topic] };
    const text = Object.entries(selected).map(([k, list]) => `# ${k}
- ${list.join("\n- ")}`).join("\n\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { tips: selected }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "kodflip-mcp",
  title: "KodFlip Animation Studio",
  version: "0.1.0",
  instructions: "Public read-only tools describing KodFlip, a browser-based frame-by-frame animation studio for kids. Use `get_app_info` for capabilities, `list_keyboard_shortcuts` for editor shortcuts, and `get_animation_tips` for kid-friendly animation guidance.",
  tools: [get_app_info_default, list_shortcuts_default, animation_tips_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
